Allow users to pass command-line arguments to scenarios
UCL/TLOmodel pull request #1373
Opened 2024-05-26 12:51 UTC by tamuri

- allow users to add their own arguments to scenarios, which will override attributes in the subclass
- add `--resume-simulation` and `--suspend-date` arguments, in anticipation of suspend/resume functionality, which is handled by BaseScenario.

I could not figure out a nice way to use the `Click` argument handling for partial handling of arguments inside of subclasses, so have implemented using argparse. `Click` will pass on any unhandled arguments to the scenario for handling upstream.

*Example*

`tlo scenario-run --draw-only src/scripts/dev/scenarios/playing_22.py --pop-size 200`

Here, only `--draw-only` is known and handled by the click decorators in `cli.py`. `--pop-size` is passed to a new scenario `parse_arguments()` method. In order for it to work, the scenario writer should have added the following to their scenario class:

```
    def add_arguments(self, parser):
        parser.add_argument('--pop-size', type=int)
```

This allows the scenario to accept the `--pop-size` argument which, in turn, sets `self.pop_size` (overriding any existing value).

2024-05-28 07:46 UTC, tamuri commented
Note: I haven't updated the `batch-submit` subcommand to handle these scenario arguments in this PR - that's for a future PR once this local-running has been tested (and suspend/resume is in??)

2024-06-03 14:10 UTC, matt-graham requested changes
Thanks this looks good in general. Have suggested some refactoring of the new `test_scenario.py` module to avoid the dependencies between the tests and a couple of other minor comments.

2024-06-03 14:10 UTC, matt-graham commented on src/tlo/scenario.py
> +                setattr(self, key, value)
This assumes we never want an argument to have value `None` - this is probably fine but we might want to document this in the `add_arguments` docstring?

2024-06-03 15:44 UTC, matt-graham approved these changes
Thanks for making the changes! Looks good to me now - I've suggested some minor clean-ups to the tests to remove now used `suspend_date` fixture and check for absence of `resume_simulation` attribute, but as I think the tests will still be valid with these present if you think better to leave in place for adding in those arguments once we get #1227 in then happy for this to go in as is.

2024-06-03 15:44 UTC, matt-graham commented on tests/test_scenario.py
> +
```suggestion
```
As no longer used

2024-06-03 15:44 UTC, matt-graham commented on tests/test_scenario.py
> +def arguments(pop_size, suspend_date):
```suggestion
def arguments(pop_size):
```

2024-06-03 15:44 UTC, matt-graham commented on tests/test_scenario.py
> +    assert not hasattr(loaded_scenario_with_parsed_arguments, 'resume_simulation')
```suggestion
```

2024-06-03 15:44 UTC, matt-graham commented on tests/test_scenario.py
> +def test_runner(tmp_path, loaded_scenario_with_parsed_arguments, pop_size, suspend_date):
```suggestion
def test_runner(tmp_path, loaded_scenario_with_parsed_arguments, pop_size):
```

2024-06-03 23:17 UTC, merged