add a utility func. of getting standard parameters for hrh historical scaling and rescaling to effective capabilities in mode 2
UCL/TLOmodel pull request #1534
Opened 2024-12-04 00:45 UTC by BinglingICL

2024-12-09 13:10 UTC, tbhallett commented
Thanks @BinglingICL  - the utility function seems very good.

What's the change in the .xlsx file?

2024-12-09 14:43 UTC, BinglingICL commented
> What's the change in the .xlsx file?

Thanks for checking Tim. The difference to master is that I have copied and added the sheet of "historical_scaling" from PR #1414, for adding the parameters of yearly scaling up factors.

2024-12-13 12:39 UTC, tbhallett requested changes

2024-12-13 12:39 UTC, tbhallett commented on resources/healthsystem/human_resources/scaling_capabilities/ResourceFile_dynamic_HR_scaling.xlsx
@BinglingICL -- this file is now in master, so I think we can remove it from this PR?

2024-12-13 14:23 UTC, BinglingICL commented on resources/healthsystem/human_resources/scaling_capabilities/ResourceFile_dynamic_HR_scaling.xlsx
Now master merged in and the resource file is the one in the master.

2024-12-13 15:10 UTC, tbhallett commented
Excellent - thank you very much for this, @BinglingICL

2024-12-13 15:12 UTC, tbhallett approved these changes

2024-12-13 16:07 UTC, merged